### PR TITLE
Replace --segmentation_image by --binary_image

### PR DESCRIPTION
**Pull request by tischi**

### CODE REVIEW

**Comment by tischi** [comment]
@wolny Could you have a look?

**Comment by wolny** [comment]
Hey @tischi. This looks good, just a one-liner :) why does it the parameter name has to be replaced though?

**Comment by tischi** [comment]
I was told by a user that it does not work with `--segmentation_image`, maybe double-check with @k-dominik ?

**Comment by wolny** [comment]
Looks like you're right @tischi. Nice spot!

**Pull request merged**
