### PR TITLE
Add ImageJ command for listing HDF5 datasets

### PR DESCRIPTION
**Pull request by emilmelnikov**
Also refactor DatasetEntry: save shape and dtype as fields, and move verboseName to the toString() method.

Closes https://github.com/ilastik/ilastik4ij/issues/93

### CODE REVIEW

**Comment by emilmelnikov** [comment]
The new command shows a table with datasets' metadata. However, I'm not sure how to work with such tables from ImageJ macro language.

I tried to use [the macro table API](https://imagej.nih.gov/ij/developer/macro/functions.html) (search for `Table Functions`), but it does not work.

**Comment by k-dominik** [comment]
Heya, this is great, I think the test failures point at some colon missing in new `toString`...:
```
<...dataset_without_axes[:] (64, 64) int64> but was:<...dataset_without_axes[] (64, 64) int64>
```

with regards to the macro table API, maybe someone on the forum can help?

**Comment by emilmelnikov** [comment]
Superseded by https://github.com/ilastik/ilastik4ij/pull/115.

**Comment by pdd2110** [comment]
Hi, thanks for adding this feature!

Any updates on how to access the scijava table via the macro language? I saw that the image.sc forum post hasn't had any activity. Even a `call `function would be helpful.

**Pull request closed without merging**
